### ISSUE TITLE
Clarification on Configuration with ECS

### ISSUE THREAD

**Issue by dentonmwood** [aws-observability/aws-otel-community#21]
Trying to add the OTEL Collector and Emitter as sidecar containers to our Java app to be able to do tracing in AWS X-Ray using the instructions [here](https://aws-otel.github.io/docs/setup/ecs). I wasn't sure what the difference between the default config and task metrics config was, so I went with the default config. Now, In X-Ray, I see an application called "SampleServer" running on port 8000. There was nothing in X-Ray before, so I assume it's picking our application up, but our application runs on a different port.

How can we specify specific configuration for our app using the sidecar container? My understanding was that we would not need to modify our application in any way for this to work, but that may be wrong.

**Comment by mxiamxia** [comment]
> I wasn't sure what the difference between the default config and task metrics config was
The default config is to setup/enable the application metrics and x-ray tracing in the collector for your application services.  And `task metrics` is to monitor the infrastructure metrics of your ECS task like network, memory metrics, etc. 

Our sample setup has also provide a [sample-app example](https://github.com/aws-observability/aws-otel-collector/blob/main/examples/ecs/ecs-fargate-sidecar.json#L24) running together with OTel Collector in ECS Task, that's why you see `SampleServer` running on port 8000. You can replace your own application docker image there and 

The sample app code is here.
https://github.com/JohnWu20/aws-xray-sdk-go-sample

You can also reference our Java Sample app [here](https://github.com/aws-observability/aws-otel-test-framework/blob/terraform/sample-apps/spark/Dockerfile#L10) which emits Metric and traces data.
