### ISSUE TITLE
Hi, Is it possible to add the ARN of the Lambda Layer to my AWS Lambda Container Image

### ISSUE THREAD

**Issue by iamcristos** [aws-observability/aws-otel-community#37]
For more context, I'm AWS lambda Container Image to handle my lambda function

**Comment by NathanielRN** [comment]
Hey @iamcristos !

This sounds like an interesting use case. I went online and found [this blog post in the "Copy the contents of a Lambda layer into a container image" section](https://aws.amazon.com/blogs/compute/working-with-lambda-layers-and-extensions-in-container-images/) which discusses steps that I think will be helpful to you.

For example, if you are using OTel Python Container images, you would want [the OTel Python Lambda Layer ARN](https://aws-otel.github.io/docs/getting-started/lambda/lambda-python). Then, you could do

```
curl $(aws lambda get-layer-version-by-arn --arn arn:aws:lambda:us-west-2:901920570463:layer:aws-otel-python38-ver-1-7-1:1 --query 'Content.Location' --output text) --output layer.zip
```

to get the contents of the Lambda Layer and add them to your Lambda function.

Another solution is to create the Lambda function with the Docker Image, and then use the `aws` cli afterwards to add the Lambda Layer. This is also explained in the blog post.

```bash
aws lambda create-function --region us-east-1 --function-name my-function \  
    --role arn:aws:iam::123456789012:role/lambda-role \
    --layers \
        "arn:aws:lambda:us-west-2:901920570463:layer:aws-otel-python38-ver-1-7-1:1" \
```

Otherwise, if you were looking for a setting that added it at once in the Docker Image it seems that the Docker Images don't support that. If that is a feature you want to request I recommend looking at the [aws-lambda-base-images GitHub Repository](https://github.com/aws/aws-lambda-base-images/blob/python3.9/Dockerfile.python3.9) where you can voice your use case 🙂 

Hope that helps!
